[placeholders.version]
prompt = "Initial version"
type = "string"
default = "0.1.0"

[placeholders.license]
prompt = "License"
type = "string"
choices = ["BSD-3-Clause", "LGPL-3.0-or-later", "Custom"]
default = "BSD-3-Clause"

[placeholders.github_username]
prompt = "Your github username"
type = "string"

[placeholders.nix]
prompt = "Enable nix files"
type = "bool"
default = true

[placeholders.exe]
prompt = "Enable executable targets"
type = "bool"
default = false

[placeholders.test]
prompt = "Enable tests"
type = "bool"
default = true

[placeholders.bench]
prompt = "Enable benchmarks"
type = "bool"
default = false

[placeholders.cabal-fmt]
prompt = "Add cabal-fmt 'expand src' hints"
type = "bool"
default = true

[conditional.'!nix']
ignore = [ "flake.nix" ]

[conditional.'!exe']
ignore = [ "app" ]

[conditional.'!test']
ignore = [ "test" ]

[conditional.'!bench']
ignore = [ "benchmark" ]
